# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2.1'

networks:
  nice:
    name: anstnsp
    ipam:
      driver: default
      config: 
        - subnet: 123.123.123.0/16

services:

  rca.orgorderer.com:
    container_name: rca.orgorderer.com
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca/crypto
      #CSR 설정 
      - FABRIC_CA_SERVER_CSR_CN=rca.orgorderer.com
      - FABRIC_CA_SERVER_CSR_HOSTS=rca.orgorderer.com
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_CA_NAME=rca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      #인증서 기간 (10년)
      - FABRIC_CA_SERVER_SIGNING_DEFAULT_EXPIRY=87600h 
      - FABRIC_CA_SERVER_SIGNING_PROFILES_TLS_EXPIRY=87600h
      - FABRIC_CA_SERVER_SIGNING_PROFILES_CA_EXPIRY=87600h
    ports:
      - 7054:7054
    command: /bin/bash -c '/scripts/start-root-ca.sh '
    volumes:
      - ../scripts:/scripts
      - ../crypto-config:/crypto-config
      - /var/hyperledger/production/ca/ca-orderer-server:/etc/hyperledger/fabric-ca/crypto
    networks:
      - nice

  rca.orgnaver.com:
    container_name: rca.orgnaver.com
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca/crypto
      #CSR 설정 
      - FABRIC_CA_SERVER_CSR_CN=rca.orgnaver.com
      - FABRIC_CA_SERVER_CSR_HOSTS=rca.orgnaver.com
      # - FABRIC_CA_SERVER_CSR_NAMES
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_CA_NAME=rca-naver
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      #인증서 기간 (10년)
      - FABRIC_CA_SERVER_SIGNING_DEFAULT_EXPIRY=87600h 
      - FABRIC_CA_SERVER_SIGNING_PROFILES_TLS_EXPIRY=87600h
      - FABRIC_CA_SERVER_SIGNING_PROFILES_CA_EXPIRY=87600h
    ports:
      - 17054:7054   
    command: /bin/bash -c '/scripts/start-root-ca.sh '
    volumes:
      - ../scripts:/scripts
      - ../crypto-config:/crypto-config
      - /var/hyperledger/production/ca/ca-naver-server:/etc/hyperledger/fabric-ca/crypto
    networks:
      - nice

  rca.orgkakao.com:
    container_name: rca.orgkakao.com
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca/crypto
      #CSR 설정 (Certificate Signing Request) 
      - FABRIC_CA_SERVER_CSR_CN=rca.orgkakao.com
      - FABRIC_CA_SERVER_CSR_HOSTS=rca.orgkakao.com
      # - FABRIC_CA_SERVER_CSR_NAMES
      #fabric-ca-server-config.yaml 설정 
      - FABRIC_CA_SERVER_DEBUG=true
      - FABRIC_CA_SERVER_CA_NAME=rca-kakao
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      #인증서 기간 (10년)
      # - FABRIC_CA_SERVER_SIGNING_DEFAULT_EXPIRY=87600h 
      # - FABRIC_CA_SERVER_SIGNING_PROFILES_TLS_EXPIRY=87600h
      # - FABRIC_CA_SERVER_SIGNING_PROFILES_CA_EXPIRY=87600
    ports:
      - 27054:7054
    command: /bin/bash -c '/scripts/start-root-ca.sh '
    volumes:
      - ../scripts:/scripts
      - ../crypto-config:/crypto-config
      - /var/hyperledger/production/ca/ca-kakao-server:/etc/hyperledger/fabric-ca/crypto
    networks:
      - nice

  orderer0.orgorderer.com:
    extends:
      file: peer-base.yaml
      service: orderer-base
    container_name: orderer0.orgorderer.com
    image: hyperledger/fabric-orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
    - ../channel-artifacts/genesis.block:/etc/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganization/orgorderer/admin/msp:/etc/hyperledger/orderer/admin/msp 
    - ../crypto-config/ordererOrganization/orgorderer/orderers/orderer0.orgorderer.com/msp:/etc/hyperledger/orderer/msp 
    - ../crypto-config/ordererOrganization/orgorderer/orderers/orderer0.orgorderer.com/tls:/etc/hyperledger/orderer/tls 
    - /var/hyperledger/production/orderer/orderer0:/var/hyperledger/production
    ports:
      - 7050:7050
    networks:
      - nice

  orderer1.orgorderer.com:
    extends:
      file: peer-base.yaml
      service: orderer-base
    # environment:
    #   - ORDERER_GENERAL_LISTENPORT=8050
    container_name: orderer1.orgorderer.com
    image: hyperledger/fabric-orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/etc/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganization/orgorderer/admin/msp:/etc/hyperledger/orderer/admin/msp 
    - ../crypto-config/ordererOrganization/orgorderer/orderers/orderer1.orgorderer.com/msp:/etc/hyperledger/orderer/msp 
    - ../crypto-config/ordererOrganization/orgorderer/orderers/orderer1.orgorderer.com/tls:/etc/hyperledger/orderer/tls 
    - /var/hyperledger/production/orderer/orderer1:/var/hyperledger/production
    ports:
      - 8050:7050
    networks:
      - nice

  orderer2.orgorderer.com:
    extends:
      file: peer-base.yaml
      service: orderer-base
    # environment:
    #   - ORDERER_GENERAL_LISTENPORT=9050
    container_name: orderer2.orgorderer.com
    image: hyperledger/fabric-orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/etc/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganization/orgorderer/admin/msp:/etc/hyperledger/orderer/admin/msp 
    - ../crypto-config/ordererOrganization/orgorderer/orderers/orderer2.orgorderer.com/msp:/etc/hyperledger/orderer/msp 
    - ../crypto-config/ordererOrganization/orgorderer/orderers/orderer2.orgorderer.com/tls:/etc/hyperledger/orderer/tls 
    - /var/hyperledger/production/orderer/orderer2:/var/hyperledger/production
    ports:
      - 9050:7050
    networks:
      - nice

  orderer3.orgorderer.com:
    extends:
      file: peer-base.yaml
      service: orderer-base
    # environment:
    #   - ORDERER_GENERAL_LISTENPORT=10050
    container_name: orderer3.orgorderer.com
    image: hyperledger/fabric-orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/etc/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganization/orgorderer/admin/msp:/etc/hyperledger/orderer/admin/msp 
    - ../crypto-config/ordererOrganization/orgorderer/orderers/orderer3.orgorderer.com/msp:/etc/hyperledger/orderer/msp 
    - ../crypto-config/ordererOrganization/orgorderer/orderers/orderer3.orgorderer.com/tls:/etc/hyperledger/orderer/tls 
    - /var/hyperledger/production/orderer/orderer3:/var/hyperledger/production
    ports:
      - 10050:7050
    networks:
      - nice

  orderer4.orgorderer.com:
    extends:
      file: peer-base.yaml
      service: orderer-base
    # environment:
    #   - ORDERER_GENERAL_LISTENPORT=10150
    container_name: orderer4.orgorderer.com
    image: hyperledger/fabric-orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/etc/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganization/orgorderer/admin/msp:/etc/hyperledger/orderer/admin/msp 
    - ../crypto-config/ordererOrganization/orgorderer/orderers/orderer4.orgorderer.com/msp:/etc/hyperledger/orderer/msp 
    - ../crypto-config/ordererOrganization/orgorderer/orderers/orderer4.orgorderer.com/tls:/etc/hyperledger/orderer/tls 
    - /var/hyperledger/production/orderer/orderer4:/var/hyperledger/production
    ports:
      - 10150:7050
    networks:
      - nice


  peer0.orgnaver.com:
    container_name: peer0.orgnaver.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orgnaver.com
      - CORE_PEER_ADDRESS=peer0.orgnaver.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgnaver.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgnaver.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgnaver.com:7051
      - CORE_PEER_LOCALMSPID=naverMSP
      # FOR OPERATIONS SERVICE 
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=peer0.orgnaver.com:9443
      # COUCHDB CONFIG
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.orgnaver.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    # depends_on:
    #   - couchdb0.orghcc.com
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/naverOrganization/orgnaver/peers/peer0/msp:/etc/hyperledger/fabric/msp 
        - ../crypto-config/naverOrganization/orgnaver/peers/peer0/tls:/etc/hyperledger/fabric/tls
        - /var/hyperledger/production/naver/peer0:/var/hyperledger/production
    ports:
      - "7051:7051"
      - "7052:7052"


  peer1.orgnaver.com:
    container_name: peer1.orgnaver.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orgnaver.com
      - CORE_PEER_ADDRESS=peer1.orgnaver.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.orgnaver.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgnaver.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgnaver.com:7051
      - CORE_PEER_LOCALMSPID=naverMSP
      # FOR OPERATIONS SERVICE 
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=peer1.orgnaver.com:9443
      # COUCHDB CONFIG
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.orgnaver.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    # depends_on:
    #   - couchdb0.orghcc.com
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/naverOrganization/orgnaver/peers/peer1/msp:/etc/hyperledger/fabric/msp 
        - ../crypto-config/naverOrganization/orgnaver/peers/peer1/tls:/etc/hyperledger/fabric/tls
        - /var/hyperledger/production/naver/peer1:/var/hyperledger/production
    ports:
      - "8051:7051"
      - "8052:7052"



  peer0.orgkakao.com:
    container_name: peer0.orgkakao.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.orgkakao.com
      - CORE_PEER_ADDRESS=peer0.orgkakao.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.orgkakao.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.orgkakao.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.orgkakao.com:7051
      - CORE_PEER_LOCALMSPID=kakaoMSP
      # FOR OPERATIONS SERVICE 
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=peer0.orgkakao.com:9443
      # COUCHDB CONFIG
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.orgnaver.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    # depends_on:
    #   - couchdb0.orghcc.com
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/kakaoOrganization/orgkakao/peers/peer0/msp:/etc/hyperledger/fabric/msp 
        - ../crypto-config/kakaoOrganization/orgkakao/peers/peer0/tls:/etc/hyperledger/fabric/tls
        - /var/hyperledger/production/kakao/peer0:/var/hyperledger/production
    ports:
      - "9051:7051"
      - "9052:7052"


  peer1.orgkakao.com:
    container_name: peer1.orgkakao.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.orgkakao.com
      - CORE_PEER_ADDRESS=peer1.orgkakao.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.orgkakao.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.orgkakao.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.orgkakao.com:7051
      - CORE_PEER_LOCALMSPID=kakaoMSP
      # FOR OPERATIONS SERVICE 
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_OPERATIONS_LISTENADDRESS=peer1.orgkakao.com:9443
      # COUCHDB CONFIG
      # - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.orgnaver.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      # - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    # depends_on:
    #   - couchdb0.orghcc.com
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/kakaoOrganization/orgkakao/peers/peer1/msp:/etc/hyperledger/fabric/msp 
        - ../crypto-config/kakaoOrganization/orgkakao/peers/peer1/tls:/etc/hyperledger/fabric/tls
        - /var/hyperledger/production/kakao/peer1:/var/hyperledger/production
    ports:
      - "10051:7051"
      - "10052:7052"

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.orgnaver.com:7051
      - CORE_PEER_LOCALMSPID=naverMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/crypto-config/naverOrganization/orgnaver/peers/peer0/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/crypto-config/naverOrganization/orgnaver/peers/peer0/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/crypto-config/naverOrganization/orgnaver/peers/peer0/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/crypto-config/naverOrganization/orgnaver/admin/msp
    # working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    working_dir: /etc/hyperledger/fabric
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/src/chaincode
        - ../crypto-config:/crypto-config
        - ../scripts:/scripts
        - ../configtx.yaml:/etc/hyperledger/fabric/configtx.yaml
        - ../channel-artifacts:/etc/hyperledger/fabric/channel-artifacts
    networks:
      - nice 

  setup:
    container_name: setup
    image: hyperledger/fabric-ca-tools
    environment:
      - ORDERER_HOME=/etc/hyperledger/orderer
      - PEER_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c '/scripts/setup-fabric.sh; sleep 99999'
    volumes:
      - ../scripts:/scripts
      - ../crypto-config:/crypto-config
      - ../:/channel-artifacts
    networks:
      - nice


  








    
