
NodeOUs:
   Enable: true
   ClientOUIdentifier:
      Certificate: cacerts/rca-orgorderer-com-7054.pem
      OrganizationalUnitIdentifier: client
   AdminOUIdentifier:
      Certificate: cacerts/rca-orgorderer-com-7054.pem
      OrganizationalUnitIdentifier: admin
   PeerOUIdentifier:
      Certificate: cacerts/rca-orgorderer-com-7054.pem
      OrganizationalUnitIdentifier: peer
   OrdererOUIdentifier:
      Certificate: cacerts/rca-orgorderer-com-7054.pem
      OrganizationalUnitIdentifier: orderer
      
   
